make release script repo cloning function more resilient
The release scripts had been assuming that a valid gerrit user was
always configured already, but this is not necessarily the case on all
nodes. Now that the constraint update job has moved to the proposal
nodes, we need to make the cloner code try to configure the gerrit user
if "git review -s" fails. We can't always take that step because it
would result in using the wrong user on the signing node and when users
run the scripts by hand (as we still do frequently to recover from
failures).

Change-Id: Ife8108f0bff4be9ab63befc5eff4289be78316f7
Signed-off-by: Doug Hellmann <doug@doughellmann.com>

diff --git a/jenkins/scripts/release-tools/functions b/jenkins/scripts/release-tools/functions
--- a/jenkins/scripts/release-tools/functions
+++ b/jenkins/scripts/release-tools/functions
@@ -122,8 +122,16 @@ function clone_repo {
     $zc $branch git://git.openstack.org $repo
 
     # Configure git-review so we can propose patches to the repo if
-    # needed.
-    (cd $repo && git review -s)
+    # needed. Some of the release scripts are still run by hand to
+    # recover from failure, in which case we don't want to set the git
+    # review user. So try to make git review work by itself first, and
+    # only if that fails update the git configuration.
+    #
+    # NOTE(dhellmann): configure_git_review is in ../common.sh, which
+    # must be sourced by the script calling this function.
+    if ! (cd $repo && git review -s); then
+        (cd $repo && configure_git_review && git review -s)
+    fi
 
     # Make sure we have all of the existing tags so we can refer to
     # them for building the release notes.
